apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ktqueue-mongodb
  name: ktqueue-mongodb-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ktqueue-mongodb
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          rbd:
            monitors:
              - localhost:6789 # your mons here
            pool: rbd
            image: ktqueue-mongodb
            secretRef:
              name: ceph-secret
            fsType: ext4
            readOnly: false
